### ISSUE TITLE
ACF - default value wird nicht übernommen

### ISSUE THREAD

**Issue by Forcase** [Forcase/wordpress-plugin_bigbluebutton#2]
Die hinterlegten default-values aus den ACF werden beim Anlegen eines neuen Raumes nicht übernommen. Weiß nicht, ob das an ACF selbst liegt oder am PlugIn.

**Comment by Forcase** [comment]
Ok, habe jetzt gecheckt, dass bei jeder Änderung die class-bigbluebutton-admin.php angepasst werden muss. Können wir das nicht eleganter lösen?

**Comment by lxbdr** [comment]
Es gibt verschiedene Möglichkeiten zu synchronisieren. Eine Alternative wäre das hier https://www.advancedcustomfields.com/resources/local-json/ allerdings liegt dieser Ordner im Theme und sorgt dafür, dass ein weiterer Ort synchronisiert werden muss.

Du kannst für die Umgebung, in der du die Felder anlegst (z. B. meet.forcase.de) den Abschnitt aus der class-bigbluebutton-admin.php löschen, dann blockiert es sich nicht während du am bauen bist
