### ISSUE TITLE
ACF - Stylised UI

### ISSUE THREAD

**Issue by Forcase** [Forcase/wordpress-plugin_bigbluebutton#3]
wie können in WP die ACF als stylised im Backend angezeigt werden? Konkret sind das die booleschen-Werte. Diese möchte ich gerne als Toggle und nicht als Checkbox angezeigt haben. Ein Beispiel findest Du unter https://www.advancedcustomfields.com/resources/true-false/. Weißt Du wie das geht?

**Comment by lxbdr** [comment]
![image](https://user-images.githubusercontent.com/24360437/83489308-82909680-a4ae-11ea-8cef-8962e8817824.png)
musst bei dem True False feld Select2 aktivieren
